---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - '[ -z "$RUBYGEMS_VERSION" ] || gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'SIMPLECOV=yes bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_deb]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=deb_puppet5
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_deb]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=deb_puppet6
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_ub]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=ub_puppet5
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_ub]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=ub_puppet6
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_el6]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=el6_puppet5
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_el6]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=el6_puppet6
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_el7]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=el7_puppet5
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[travis_el7]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      dist: trusty
      env: PLATFORMS=el7_puppet6
      rvm: 2.5.3
      script: ["bundle exec rake litmus:acceptance:parallel"]
      services: docker
      stage: acceptance
      sudo: required
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
  slack:
    secure: mArhZST03ryygJmu2qwmgyUYwTYTSOdHxgAsvkgeiHFOD5ffYkJPxQq0z46npYpqtbV68Kkd7rHpI6m9n2U1H3hCZB6Fun7k7wEyTvSg9XYymO1boeyd5STvguJ9anMrLTA/vLYuB4S8J+22oYzvmOyeeWsyYDJiBjPJb+k/IxZyqmYQA1mYtrlawewQMTZx2D5i3B7pTYcoVqfAQaIXoYFTiIwgdjdl8dANFEFj1zMFT2PVOiobhE8serTFYyL4V6vMLJsLWtsxssHyzH9quEaS9kDXl6ixxef+WtB87x9ucCMDB18EkC/M2Ppb9Vs4cZYesE687WZYrCkFdrLkk3+Z51b/cwrIuJlk81i5FzomNJJvglLzWDkl0Z2YCNggwmg/FQWZjjRR7nbZVyyp4b9oUigYbWRZL4YDNivEQ8j7gKLaoYZ8O20tPcO3DjFhVV6Ide+ANMg67yXS82Cr4Th5D/ViFmDUuEhjFlkIGjpeBIvHjzNcwH/1F9q7n9/V0IApt0hvO22NcBpV0VdvFqAqyvbQgpL4lRo6b9Y91aOmYE5xTtLj1DRx4Munss/K5Y/Bz8LNqGpJ/CYNCWr/OmtT5wI7S5qJgJDGG12d7zRUS06hI8P/10aB/4JvJs0FyMyqRqlIYsHvqXHWmj+JZ+k4va0AeEggKa754+FJR0c=
